apiVersion: apps/v1
kind: Deployment
metadata:
    name: prometheus-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: prometheus-server
    template:
        metadata:
          labels:
            app: prometheus-server
        spec:
            containers:
            - name: prometheus
              image: prom/prometheus:v2.2.1
              ports:
              - containerPort: 9090
              volumeMounts:
              - name: prometheus-config-volume
                mountPath: /etc/prometheus/
              #- name: prometheus-storage-volume
              #  mountPath: /prometheus/
            volumes:
            - name: prometheus-config-volume
              persistentVolumeClaim:
                claimName: prometheus-pvc

            # - name: prometheus-storage-volume
            #   emptyDir: {}

~
