apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: monitoring
  labels:
    name: prometheus-server-conf
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      #- /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          #- "alertmanager.monitoring.svc:9093"
    scrape_configs:
      - job_name: 'prometheus'        
        static_configs:
        - targets: ['localhost:9090']
      
      - job_name: 'targets'
        static_configs:
        - targets: ['ws1:9100']

      - job_name: 'kube-state-metrics'                                # Job to get the kubernetes pods, nodes, PV, PVC....metrics
        static_configs:
        - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            regex: '([^:]+)(:[0-9]+)?'
            replacement: '${1}'
