apiVersion: apps/v1
kind: Deployment
metadata: 
    name: grafana-deployment
spec:
    replicas: 2
    selector:
        matchLabels:
            app: grafana-server
    template:
        metadata:
          labels:
            app: grafana-server
        spec:
            containers:
            - name: grafana  
              image: grafana/grafana:latest
              ports:
              - containerPort: 3000
              volumeMounts:
              - name: grafana-config-volume
                mountPath: /etc/grafana/
              - name: grafana-storage-volume
                mountPath: /grafana/
            volumes:
            - name: grafana-config-volume
              configMap:
                defaultMode: 420
                name: grafana-server-conf
                
            - name: grafana-storage-volume
              emptyDir: {}
