apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
spec:
  selector:
    app: grafana-server
  type: NodePort
  ports:
    - port: 8081
      targetPort: 3000
      nodePort: 30001
